name: bharat_mandi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  pdf: ^3.10.7
  printing: ^5.12.0


  # ✅ UI & Core
  cupertino_icons: ^1.0.2
  provider: ^6.1.2

  # ✅ POWERSYNC (Offline-First Sync Database)
  powersync: ^1.4.0

  # ✅ Utilities
  path_provider: ^2.1.5
  path: ^1.9.0
  intl: ^0.19.0
  uuid: ^4.2.1
  connectivity_plus: ^5.0.0

  # ✅ Database (PowerSync uses it internally)
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/NotoSansDevanagari-Regular.ttf
    - assets/fonts/NotoSansDevanagari-Bold.ttf
